# This is a workflow to set up Chrome Remote Desktop on Windows

name: Chrome Remote Desktop Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  chrome-remote-desktop:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Chrome Remote Desktop
      run: |
        start /wait msiexec /i "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" /quiet
        "%PROGRAMFILES(X86)%\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0ATx3LY7ULu1D_rf1awi2VHNYmYkLY0ubpC5DWeruZCBxNQiCPLIpxzkMSCijy6AF64ofKw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=%COMPUTERNAME%
      shell: cmd
