# This is a basic workflow to help you get started with Actions

name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: |
        $P = $env:TEMP + '\chromeremotedesktophost.msi'
        Invoke-WebRequest 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi' -OutFile $P
        Start-Process $P -Wait
        Remove-Item $P
        $P = $env:TEMP + '\chrome_installer.exe'
        Invoke-WebRequest 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile $P
        Start-Process -FilePath $P -Args '/install' -Verb RunAs -Wait
        Remove-Item $P
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: |
        $i = 700
        do {
            Write-Host $i
            Start-Sleep -Seconds 700
            $i--
        } while ($i -gt 0)
