name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Downloading & Installing Essentials
      run: |
          Invoke-WebRequest -Uri "https://gitlab.com/yasirsiddiqui/crd-rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

    - name: Change Password
      run: cmd /c show.bat
            
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}

    - name: Time Counter
      run: cmd /c loop.bat
